emitter:
    emissionAngle: 0.000000
    emissionRange: 100.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "sparks"
    radius: 2.000000
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "rect"
