emitter:
    emissionRange: 0.000000
    emissionVector: [1.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "window_glow"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
