emitter:
    emissionAngle: 0.000000
    emissionRange: 10.000000
    emissionVector: [-1.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "smoke"
    shortEffect: false
    size: [0.000000, 100.000000, 600.000000]
    type: "rect"
