emitter:
    emissionAngle: 1.000000
    emissionRange: 20.000000
    emissionVector: [-0.900000, -0.600000, 0.000000]
    emissionVectorInverted: true
    name: "fire"
    radius: 1.000000
    shortEffect: false
    size: [0.000000, 1.200000, 0.000000]
    type: "point"
