emitter:
    emissionAngle: 0.000000
    emissionRange: 30.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "snow"
    shortEffect: false
    size: [0.100000, 0.000000, 4.000000]
    type: "rect"
layer0:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.000000, 0.605800, 0.990000, 0.000000]
    blending: 1
    colorOverLife: [193.000000, 213.000000, 231.000000, 255.000000]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.200000
    force0: [0.000000, -0.300000, -2.000000]
    force1: [0.000000, 0.000000, 0.000000]
    forceCount: 2
    forceOverLife0: [0.000000, 0.000000, 1.000000, 0.500000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 6.000000
    loopEndTime: 5.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "snow"
    number: 30.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [2.008700, 2.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [2.000000, 2.000000]]
    spin: 20.000000
    spinVariation: 20.000000
    sprite: "../../../Gfx/Particles/alpha/fog_white"
    startTime: 0.000000
    type: "layer"
    velocity: 0.010000
