emitter:
    emissionRange: 0.000000
    emissionVector: [0.000000, 0.000000, 0.500000]
    emissionVectorInverted: true
    name: "Djin"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    blending: 3
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    innerEmitterPath: "Djin_iner.yaml"
    isLong: false
    isLooped: false
    layerType: "superEmitter"
    life: 7.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "Djin_iner"
    number: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
