emitter:
    emissionRange: 0.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "lamp"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: 0.000000
    blending: 3
    colorOverLife: [206.000000, 209.000000, 255.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 4.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "single"
    life: 6.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "lightbulb2"
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.400000, 0.500000]
    sprite: "../../../Gfx/Particles/hangar_ny_2017/lightbulb"
    startTime: 0.000000
    type: "layer"
layer1:
    activeLODS: [1, 1, 1, 1]
    blending: 3
    colorOverLife: [206.000000, 209.000000, 255.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 4.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "single"
    life: 6.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "lightbulb"
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.400000, 0.500000]
    sprite: "../../../Gfx/Particles/hangar_ny_2017/lightbulb"
    startTime: 0.000000
    type: "layer"
layer2:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: 1.000000
    blending: 3
    colorOverLife: [206.000000, 209.000000, 255.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 4.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "single"
    life: 6.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "glow"
    particleOrientation: 1
    pivotPoint: [0.000000, 0.400000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.400000, 0.400000]
    sprite: "../../../Gfx/Particles/hangar_ny_2017/glow_low2"
    startTime: 0.000000
    type: "layer"
layer3:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: 1.000000
    blending: 3
    colorOverLife: [206.000000, 209.000000, 255.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 4.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "single"
    life: 6.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "glow1"
    particleOrientation: 1
    pivotPoint: [0.000000, 0.400000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [0.400000, 0.400000]
    sprite: "../../../Gfx/Particles/hangar_ny_2017/glow_low2"
    startTime: 0.000000
    type: "layer"
